[package]
name = "ptah"
version = "0.1.0"
edition = "2024"

[dependencies]
gumdrop = "0.8.1"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde-semver = "0.2.1"
serde_json = "1.0.140"
walkdir = "2.5.0"
